### ISSUE TITLE
AY-7281_Use Publisher instead of creator tool and pyblish pype

### ISSUE THREAD

**Issue by iLLiCiTiT** [ynput/ayon-harmony#12]
### Is there an existing issue for this?

- [x] I have searched the existing issues and added correct labels.

### Please describe the feature you have in mind and explain what the current shortcomings are?

Convert integration to use new create plugins and use Publisher tool instead of create tool and pyblish pype.

**Comment by tanh609** [comment]
This would be great as the legacy publish does not provide a good way to see the error feedback. Please let me know how can I help with this.

**Comment by BigRoy** [comment]
Started a draft with https://github.com/ynput/ayon-harmony/pull/17

From there on out the heavier work I think is in the actual Harmony API and setting up the actual scene data as we need it. So with a bit of luck someone else can take it from there with just some guidance. :)

**Comment by marvill85** [comment]
Hello,
we here at Incognito studio Prague would also appreciate Harmony addon to roll ahead.
Unlike tanh609, we use Ftrack, but we are struggling to get published versions properly into ftrack database etc.

**Comment by kalisp** [comment]
Solved by https://github.com/ynput/ayon-harmony/pull/19
